export default {
  fId: 0,
  scenicLists: [],
  map: {},
  markercsgroup: null,
  markerzxgroup: null,
  markerwifigroup: null,
  markerfdgroup: null,
  markerscenicgroup: null,
  markermonitorgroup: null,
  fVideo: '',
  isPack: false,
  isPackShow1: true,
  isPackShow2: true,
  isPackShow3: true,
  isTicket: false,
  isTicketShow1: true,
  isTicketShow2: true,
  isMonitor: false,
  isMonitorShow1: true,
  isMonitorShow3: true,
  isMonitorShow2: true,
}
